### ISSUE TITLE
Hacer el footer

### ISSUE THREAD

**Issue by Ponchu** [FEZR85/proyecto#2]
Hacer el footer, generalizar encabezados (fondo verde, letras blancos), alinear textos.

**Comment by FEZR85** [comment]
El footer si lo vas a dejar con los copyright dejalo fuera del div class content y que abarque el 100% de las pantallas, el que iba dentro es uno que solamente llevaba un tip como si fuera propaganda.
Los encabezados si les daras el background modificalos para que no se salgan de div class content en el css.

**Comment by Ponchu** [comment]
Realmente es de prueba el texto, mejor quisiera que comentaramos lo que vamos a ingresar en el footer, pensé dejarlo dentro de ese div debido a que en muchas de las vistas que tenemos no son de mucha altura, y al colocar el footer debajo del div que contiene todo ( el que está sombreado ) se ve mal, como si fuera una barra de información metida a la fuerza a medias, y dentro del div simplemente se limita a la longitud del contenido.

**Comment by FEZR85** [comment]
Se pueden hacer dos, uno que sea como el que esta en todas las paginas, ve el de aqui de github. Para el de tips que solo aparesca en las paginas relacionadas a los cursos (logueado o no) y en el index, en las demas como los formularios lo omitimos porque ahi no es necesario mostrar un "TIP".

**Comment by Ponchu** [comment]
Bueno, entonces haré un nuevo issue para indicar el tener 2 footer: el del sitio en general y el de tips que iría en ciertas páginas.
